### ISSUE TITLE
Link to official version

### ISSUE THREAD

**Issue by amandabee** [duckduckgrayduck/Klaxon#10]
Somewhere in the Readme for this repo, we should probably redirect folks to the official repo at: https://github.com/MuckRock/Klaxon/issues (I looked and couldn't find it.)

**Comment by duckduckgrayduck** [comment]
This is my personal repository where I work on changes for Klaxon before deploying them. This is not the repo that folks see when they click on "View Source"

**Comment by amandabee** [comment]
It might be worth tagging the MuckRock repo in your Readme? I only found this and Marshall project when I searched GitHub for klaxon. 

On November 7, 2024 6:56:34 PM PST, Sanjin ***@***.***> wrote:
>
>This is my personal repository where I work on changes for Klaxon before deploying them. This is not the repo that folks see when they click on &quot;View Source&quot; 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/duckduckgrayduck/Klaxon/issues/10#issuecomment-2463658902
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***&gt;

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
