### ISSUE TITLE
Possible Improvements

### ISSUE THREAD

**Issue by amandabee** [duckduckgrayduck/Klaxon#9]
I recently set up my first ever Klaxon run in the DocumentCloud Add-On and found a few things a bit confusing:

1) When I first set up the add on, I got a notice that said "Klaxon Cloud: Site Monitor and Alerts - In Progress" and "Checking the site for updates... " but it wasn't obvious whether I should wait to confirm that it would work or whether this was just "Klaxon is running now." 
![image](https://github.com/user-attachments/assets/7589f162-1b70-48b3-821d-e9ca4a38e00c)
I think the initial message should be something like "We're preparing the baseline." or something. The action at that moment isn't really "Checking for updates".

1a) To get the screenshot above, I tried setting Klaxon up on another page, which failed (I'm not surprised, it was a non public Notion URL). The failure indication doesn't give me any information on how I might investigate the nature of the failure. 
![image](https://github.com/user-attachments/assets/ae29b584-d47e-4769-a83c-0776d910bf95). And looking at my Schedule and History I don't see anything more there, either. Just an indication of failure. 
![image](https://github.com/user-attachments/assets/74790ed2-9e4b-4c00-8507-004301e241a4)

1b) Once the snapshot is stored, I got an email with the details but the history run  just says "Site archived on the Wayback machine for the first time." -- it  would be nice to get a link to either the snapshot or at least the part of the Wayback Machine where I can see it the snapshot. 

2) When I got my email update indicating that changes had been detected, I could get to the Diff and I could get to the Wayback machine but I don't see a way to get to my Klaxon settings to either disable Klaxon or refine what I'm tracking.  We definitely want people to disable monitors they're not interested in using anymore, and we should make it easier to get straight to the place where you can tweak your settings. 
![image](https://github.com/user-attachments/assets/ae3ed52b-93cb-4876-8238-1255e1666171)

3) It took me a while to figure out that I need to set "Runs on a schedule" to "Disable" if I want to turn it off. I think we should make it easier to disable a Klaxon run.

**Comment by amandabee** [comment]
Item 1 looks different in https://next.www.documentcloud.org/  but the phrasing is the same. 

![image](https://github.com/user-attachments/assets/f6fbd091-aacb-4554-9f1b-b73ffb148809)

**Comment by duckduckgrayduck** [comment]
Copied this over to: https://github.com/MuckRock/Klaxon/issues/15 for tracking
